# font 
font_family JetBrainsMono-SemiBold
font_size 14

# theme
foreground #AE9DD6
background #000000
url_color #34bbe0

# Cursor
cursor #A4D5A6

# opacity 
background_opacity 0.65

# window decor
hide_window_decorations no

# blur
background_blur 50
